"""Utilities for persona analysis and adversarial evidence detection."""

from __future__ import annotations

from collections import Counter
from typing import Iterable
from typing import Mapping
from typing import Sequence


def find_ignored_high_credibility_facts(
    persona_analyses: Iterable[Mapping[str, object]],
    cer_registry: Sequence[Mapping[str, object]],
    *,
    ignore_threshold: float = 0.6,
    min_credibility: float = 0.85,
) -> list[Mapping[str, object]]:
  """Identify CER facts ignored by a majority of personas despite high credibility.

  Args:
    persona_analyses: Iterable of persona analysis payloads generated by dynamic
      persona agents.
    cer_registry: Current Central Evidence Registry entries.
    ignore_threshold: Minimum proportion of personas that must ignore a fact for
      it to be considered a blind spot.
    min_credibility: Minimum credibility score for ignored facts to be flagged.

  Returns:
    List of CER fact dicts that meet the blind spot criteria.
  """
  analyses = list(persona_analyses)
  if not analyses:
    return []

  ignored_counts: Counter[str] = Counter()
  for analysis in analyses:
    evidence = analysis.get('evidence', {})
    ignored_items = evidence.get('ignored', []) if isinstance(evidence, Mapping) else []
    for item in ignored_items or []:
      fact_id = None
      if isinstance(item, Mapping):
        fact_id = item.get('fact_id')
      elif isinstance(item, str):
        fact_id = item
      if fact_id:
        ignored_counts[fact_id] += 1

  if not ignored_counts:
    return []

  threshold = max(1, int(len(analyses) * ignore_threshold))
  ignored_ids = {
      fact_id
      for fact_id, count in ignored_counts.items()
      if count >= threshold
  }

  if not ignored_ids:
    return []

  high_credibility_facts: list[Mapping[str, object]] = []
  for fact in cer_registry:
    fact_id = fact.get('fact_id')
    credibility = fact.get('credibility_score')
    if (
        fact_id in ignored_ids
        and isinstance(credibility, (int, float))
        and credibility >= min_credibility
    ):
      high_credibility_facts.append(fact)

  return high_credibility_facts

